version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - '1389:389'
      - '1636:636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin